on: [pull_request]
name: mabl

jobs:
  test:
    name: Mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

      - name: Run Tests
        run: npm test

      - name: Compile Typescript
        run: npm run build

      - name: Run mabl tests against deployment
        id: mabl-test-deployment
        uses: ./
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: D6uz-lhAGBYuTTc6Jj_w0Q-a
          environment-id: I9tfo2dWd7WSigXcO91feA-e
          browser-types: |
            chrome
          plan-labels: |
            canary
            smoke-test
          http-headers: |
            X-Test-Header-1: 1234
            X-Test-Header-2: 5678